# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(150F11)
$foreground = rgb(F9AFB6)
$color0 = rgb(3D3739)
$color1 = rgb(1A050E)
$color2 = rgb(1A050E)
$color3 = rgb(210610)
$color4 = rgb(601623)
$color5 = rgb(89212F)
$color6 = rgb(B31422)
$color7 = rgb(EF858E)
$color8 = rgb(A75D63)
$color9 = rgb(230613)
$color10 = rgb(230613)
$color11 = rgb(2C0816)
$color12 = rgb(801E2E)
$color13 = rgb(B72C3F)
$color14 = rgb(EF1B2E)
$color15 = rgb(EF858E)
