# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F9AFB6
background         #150F11
cursor             #8E5B64

active_tab_foreground     #150F11
active_tab_background     #F9AFB6
inactive_tab_foreground   #F9AFB6
inactive_tab_background   #150F11

active_border_color   #F9AFB6
inactive_border_color #150F11
bell_border_color     #1A050E

color0      #3D3739
color1		#1A050E
color2		#1A050E
color3		#210610
color4		#601623
color5		#89212F
color6		#B31422
color7		#EF858E
color8		#A75D63
color9		#230613
color10		#230613
color11		#2C0816
color12		#801E2E
color13		#B72C3F
color14		#EF1B2E
color15		#EF858E
